// Code generated by "stringer -type=FlagType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[None-0]
	_ = x[Int-1]
	_ = x[Bool-2]
	_ = x[String-3]
	_ = x[Duration-4]
}

const _FlagType_name = "NoneIntBoolStringDuration"

var _FlagType_index = [...]uint8{0, 4, 7, 11, 17, 25}

func (i FlagType) String() string {
	if i < 0 || i >= FlagType(len(_FlagType_index)-1) {
		return "FlagType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FlagType_name[_FlagType_index[i]:_FlagType_index[i+1]]
}
