// Code generated by "habu -type Options -viper true"; DO NOT EDIT.

package main

import (
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

func PrepareOptionsFlags(c *cobra.Command, v *viper.Viper) {
	fs := c.Flags()
	ps := c.PersistentFlags()
	ps.StringP("config", "c", "", "config file")
	v.BindPFlag("Config", ps.Lookup("config"))
	v.BindEnv("Config")
	fs.StringP("from-type", "f", "", "convert from [fwv|csv]")
	v.BindPFlag("FromType", fs.Lookup("from-type"))
	v.BindEnv("FromType")
	fs.StringP("to-type", "t", "", "convert to [fwv|csv]")
	v.BindPFlag("ToType", fs.Lookup("to-type"))
	v.BindEnv("ToType")
	fs.BoolP("no-width", "W", false, "NOT use char width")
	v.BindPFlag("NoWidth", fs.Lookup("no-width"))
	v.BindEnv("NoWidth")
	fs.BoolP("eaa-half-width", "E", false, "treat East Asian Ambiguous as half width")
	v.BindPFlag("EaaHalfWidth", fs.Lookup("eaa-half-width"))
	v.BindEnv("EaaHalfWidth")
	fs.BoolP("show-column-ranges", "r", false, "show column ranges")
	v.BindPFlag("ShowColumnRanges", fs.Lookup("show-column-ranges"))
	v.BindEnv("ShowColumnRanges")
	fs.BoolP("no-trim", "T", false, "NOT trim whitespaces")
	v.BindPFlag("NoTrim", fs.Lookup("no-trim"))
	v.BindEnv("NoTrim")
	fs.BoolP("color", "C", false, "colorize output")
	v.BindPFlag("Color", fs.Lookup("color"))
	v.BindEnv("Color")
	fs.BoolP("no-color", "M", false, "NOT colorize output (monochrome)")
	v.BindPFlag("NoColor", fs.Lookup("no-color"))
	v.BindEnv("NoColor", "NO_COLOR")
	fs.StringP("whitespaces", "s", " ", "characters treated as whitespace")
	v.BindPFlag("Whitespaces", fs.Lookup("whitespaces"))
	v.BindEnv("Whitespaces")
	fs.StringP("delimiter", "d", " ", "delimiter used for FWV output")
	v.BindPFlag("Delimiter", fs.Lookup("delimiter"))
	v.BindEnv("Delimiter")
}
