// Code generated by "habu -type Options -viper true"; DO NOT EDIT.

package main

import (
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

func PrepareOptionsFlags(c *cobra.Command, v *viper.Viper) {
	c.PersistentFlags().StringP("config", "c", "", "config file")
	v.BindPFlag("Config", c.PersistentFlags().Lookup("config"))
	v.BindEnv("Config")
	c.Flags().StringP("from-type", "f", "", "convert from [fwv|csv]")
	v.BindPFlag("FromType", c.Flags().Lookup("from-type"))
	v.BindEnv("FromType")
	c.Flags().StringP("to-type", "t", "", "convert to [fwv|csv]")
	v.BindPFlag("ToType", c.Flags().Lookup("to-type"))
	v.BindEnv("ToType")
	c.Flags().BoolP("no-width", "W", false, "NOT use char width")
	v.BindPFlag("NoWidth", c.Flags().Lookup("no-width"))
	v.BindEnv("NoWidth")
	c.Flags().BoolP("eaa-half-width", "E", false, "treat East Asian Ambiguous as half width")
	v.BindPFlag("EaaHalfWidth", c.Flags().Lookup("eaa-half-width"))
	v.BindEnv("EaaHalfWidth")
	c.Flags().BoolP("show-column-ranges", "r", false, "show column ranges")
	v.BindPFlag("ShowColumnRanges", c.Flags().Lookup("show-column-ranges"))
	v.BindEnv("ShowColumnRanges")
	c.Flags().BoolP("no-trim", "T", false, "NOT trim whitespaces")
	v.BindPFlag("NoTrim", c.Flags().Lookup("no-trim"))
	v.BindEnv("NoTrim")
	c.Flags().BoolP("color", "C", false, "colorize output")
	v.BindPFlag("Color", c.Flags().Lookup("color"))
	v.BindEnv("Color")
	c.Flags().BoolP("no-color", "M", false, "NOT colorize output (monochrome)")
	v.BindPFlag("NoColor", c.Flags().Lookup("no-color"))
	v.BindEnv("NoColor", "NO_COLOR")
	c.Flags().StringP("whitespaces", "s", " ", "characters treated as whitespace")
	v.BindPFlag("Whitespaces", c.Flags().Lookup("whitespaces"))
	v.BindEnv("Whitespaces")
	c.Flags().StringP("delimiter", "d", " ", "delimiter used for FWV output")
	v.BindPFlag("Delimiter", c.Flags().Lookup("delimiter"))
	v.BindEnv("Delimiter")
}
